name: deploy
on:
  push:
    branches:
      - main
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v5
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws-eusc:iam::074779644207:role/GitHubDeployRole
          role-session-name: GitHubAction
          aws-region: eusc-de-east-1
          audience: sts.amazonaws.eu
      - name: Deploy
        run: |
          aws cdk deploy
